/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Analyze
         * @description Transcribe and analyze without generating a reply.
         *
         *     This is the endpoint that makes the project's central claim inspectable
         *     side by side: `transcript` is what a conventional pipeline would have kept,
         *     `acoustic` is everything it would have thrown away.
         */
        post: operations["analyze_api_analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout All */
        post: operations["logout_all_api_auth_logout_all_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_auth_me_get"];
        put?: never;
        post?: never;
        /**
         * Delete Me
         * @description Hard delete. No `is_deleted` flag.
         *
         *     Someone asking to be erased is not asking to be hidden. Turns are removed
         *     explicitly because SQLite does not enforce ON DELETE CASCADE unless foreign
         *     keys are switched on per connection, and relying on that would leave
         *     orphaned transcripts behind.
         */
        delete: operations["delete_me_api_auth_me_delete"];
        options?: never;
        head?: never;
        /** Update Me */
        patch: operations["update_me_api_auth_me_patch"];
        trace?: never;
    };
    "/api/auth/me/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export Me
         * @description Everything this account owns, and nothing else.
         */
        get: operations["export_me_api_auth_me_export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change Password */
        post: operations["change_password_api_auth_me_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh */
        post: operations["refresh_api_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["register_api_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/ws-ticket": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ws Ticket
         * @description A short-lived, single-use ticket for opening a WebSocket.
         *
         *     Browsers cannot set headers on a WebSocket, and a JWT in the query string
         *     would be written into access logs and browser history. This is neither: it
         *     is worthless 30 seconds after issue and worthless after one use.
         */
        post: operations["ws_ticket_api_auth_ws_ticket_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Chat
         * @description One typed turn through the cascade.
         */
        post: operations["chat_api_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat/audio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Chat Audio
         * @description One spoken turn, uploaded rather than streamed.
         *
         *     The streaming socket is the real interface; this is the one that is easy to
         *     drive from a script, which makes it what the evaluation harness and the
         *     acoustic-analyzer tests use.
         */
        post: operations["chat_audio_api_chat_audio_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/corpus": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Corpus Status */
        get: operations["corpus_status_api_corpus_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/corpus/ingest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ingest */
        post: operations["ingest_api_corpus_ingest_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/corpus/manifest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Manifest
         * @description What is indexed, by source.
         *
         *     Reconcile this against data/corpus/SOURCES.md before writing the report: a
         *     document indexed but unlogged has no provenance, and one logged but
         *     unindexed is backing no answer.
         */
        get: operations["manifest_api_corpus_manifest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/corpus/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search
         * @description Query retrieval directly.
         *
         *     The fastest way to check whether a poor answer came from bad retrieval or
         *     bad generation, which is otherwise hard to tell apart.
         */
        get: operations["search_api_corpus_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/schema/acoustic": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Acoustic Schema
         * @description The S1/M5 contract, served as JSON Schema.
         *
         *     Track M validates the classifier's output against this, so the two tracks
         *     cannot drift apart without a test failing.
         */
        get: operations["acoustic_schema_api_schema_acoustic_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sessions */
        get: operations["list_sessions_api_sessions_get"];
        put?: never;
        /** Create Session */
        post: operations["create_session_api_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Progress
         * @description Trend across this account's recent sessions.
         *
         *     Registered before `/{session_id}` so the literal path is not captured by
         *     the parameterised route.
         */
        get: operations["progress_api_sessions_progress_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Session */
        get: operations["get_session_api_sessions__session_id__get"];
        put?: never;
        post?: never;
        /** Delete Session */
        delete: operations["delete_session_api_sessions__session_id__delete"];
        options?: never;
        head?: never;
        /** Rename Session */
        patch: operations["rename_session_api_sessions__session_id__patch"];
        trace?: never;
    };
    "/api/sessions/{session_id}/end": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** End Session */
        post: operations["end_session_api_sessions__session_id__end_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Session Metrics */
        get: operations["session_metrics_api_sessions__session_id__metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Status
         * @description What the system can actually do right now.
         *
         *     The UI reads this on load to decide whether to offer the live coach, and it
         *     is the fastest way to see which half of the stack is up.
         */
        get: operations["status_api_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness. Deliberately cheap — no model is touched.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AcousticProfile
         * @description Everything the acoustic branch knows about one user utterance.
         */
        AcousticProfile: {
            /**
             * Analyzed
             * @default false
             */
            analyzed: boolean;
            /**
             * Dominant Event
             * @description The event kind that occupied the most time.
             *
             *     Weighted by duration, not by count. Counting would let three 400 ms
             *     repetitions outvote a single 1.5 s block, and the coach would be told
             *     to watch for repeated words when what actually happened is that the
             *     speaker got stuck — the one situation where "give them room, do not
             *     fill the pause" matters most. Time occupied is the better proxy for
             *     what dominated the utterance, and it still surfaces filler guidance for
             *     someone whose speech is mostly interjections.
             */
            readonly dominant_event: string | null;
            /**
             * Duration Ms
             * @default 0
             */
            duration_ms: number;
            /**
             * Dysfluent Ms
             * @description Total time occupied by detected events.
             *
             *     Overlapping events are merged so two detectors firing on one moment do
             *     not double-count it.
             */
            readonly dysfluent_ms: number;
            /** Event Counts */
            readonly event_counts: {
                [key: string]: number;
            };
            /** Events */
            events?: components["schemas"]["DysfluencyEvent"][];
            /**
             * Fluency Load
             * @description Share of the utterance occupied by dysfluency events, 0.0–1.0.
             *
             *     Deliberately *not* a severity score. It drives one thing: how far the
             *     coach slows its own voice. See `suggested_speech_rate`.
             */
            readonly fluency_load: number;
            prosody?: components["schemas"]["ProsodyMetrics"];
            /**
             * Schema Version
             * @default 1.0
             */
            schema_version: string;
            /**
             * Source
             * @default unavailable
             */
            source: string;
        };
        /**
         * AuthResponse
         * @description The access token is returned in the body, never set as a cookie.
         *
         *     It is held in memory by the client and dies with the tab; the refresh
         *     token is the HttpOnly cookie, and is the only thing that survives a reload.
         */
        AuthResponse: {
            /** Access Token */
            access_token: string;
            /** Expires In */
            expires_in: number;
            user: components["schemas"]["UserOut"];
        };
        /** Body_analyze_api_analyze_post */
        Body_analyze_api_analyze_post: {
            /** Audio */
            audio: string;
        };
        /** Body_chat_audio_api_chat_audio_post */
        Body_chat_audio_api_chat_audio_post: {
            /**
             * Audio
             * @description Mono WAV
             */
            audio: string;
            /** Session Id */
            session_id?: string | null;
        };
        /** ChatRequest */
        ChatRequest: {
            /** Llm Variant */
            llm_variant?: string | null;
            /** Message */
            message: string;
            /** Session Id */
            session_id?: string | null;
            /**
             * Skip Retrieval
             * @default false
             */
            skip_retrieval: boolean;
        };
        /** ChatResponse */
        ChatResponse: {
            acoustic?: components["schemas"]["AcousticProfile"] | null;
            /** Citations */
            citations?: components["schemas"]["Citation"][];
            /**
             * Grounded
             * @default true
             */
            grounded: boolean;
            /**
             * Llm Variant
             * @default base
             */
            llm_variant: string;
            mode: components["schemas"]["Mode"];
            /** Reply */
            reply: string;
            /** Session Id */
            session_id: string;
            /** Timings */
            timings?: components["schemas"]["StageTiming"][];
            /**
             * Total Ms
             * @default 0
             */
            total_ms: number;
            /** Turn Id */
            turn_id: number;
        };
        /**
         * Citation
         * @description One retrieved chunk backing a claim in the reply.
         */
        Citation: {
            /** Chunk Index */
            chunk_index?: number | null;
            /**
             * Excerpt
             * @default
             */
            excerpt: string;
            /** Score */
            score?: number | null;
            /** Source */
            source: string;
            /** Title */
            title?: string | null;
        };
        /** DeleteAccountRequest */
        DeleteAccountRequest: {
            /** Current Password */
            current_password: string;
        };
        /**
         * DysfluencyEvent
         * @description One detected acoustic event, located in time within the utterance.
         */
        DysfluencyEvent: {
            /**
             * Confidence
             * @default 1
             */
            confidence: number;
            /** Duration Ms */
            readonly duration_ms: number;
            /** End Ms */
            end_ms: number;
            kind: components["schemas"]["DysfluencyKind"];
            /** Start Ms */
            start_ms: number;
        };
        /**
         * DysfluencyKind
         * @description The five SEP-28k event classes, plus a catch-all.
         *
         *     Names mirror the SEP-28k label set so Track M's training code and this
         *     schema stay in step without a translation table.
         * @enum {string}
         */
        DysfluencyKind: "block" | "prolongation" | "sound_repetition" | "word_repetition" | "interjection" | "unsure";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LoginRequest */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /**
         * Mode
         * @description Which path produced a turn.
         * @enum {string}
         */
        Mode: "live" | "knowledge" | "text";
        /** PasswordChangeRequest */
        PasswordChangeRequest: {
            /** Current Password */
            current_password: string;
            /** New Password */
            new_password: string;
        };
        /** ProgressOut */
        ProgressOut: {
            /** Points */
            points?: components["schemas"]["ProgressPoint"][];
            /**
             * Sessions
             * @default 0
             */
            sessions: number;
            /**
             * Total Practice Ms
             * @default 0
             */
            total_practice_ms: number;
        };
        /** ProgressPoint */
        ProgressPoint: {
            /** Mean Fluency Load */
            mean_fluency_load: number;
            /** Mean Speech Rate Wpm */
            mean_speech_rate_wpm?: number | null;
            /** Session Id */
            session_id: string;
            /** Spoken Turns */
            spoken_turns: number;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
        };
        /**
         * ProsodyMetrics
         * @description Continuous delivery measurements over the whole utterance.
         *
         *     These carry the information a transcript cannot: how fast, how evenly, and
         *     with how much pitch movement the speaker delivered the words.
         */
        ProsodyMetrics: {
            /** Articulation Rate Sps */
            articulation_rate_sps?: number | null;
            /** Energy Variation */
            energy_variation?: number | null;
            /** Longest Pause Ms */
            longest_pause_ms?: number | null;
            /** Mean Pause Ms */
            mean_pause_ms?: number | null;
            /** Pitch Mean Hz */
            pitch_mean_hz?: number | null;
            /** Pitch Variation */
            pitch_variation?: number | null;
            /** Speech Rate Wpm */
            speech_rate_wpm?: number | null;
        };
        /** RegisterRequest */
        RegisterRequest: {
            /** Display Name */
            display_name?: string | null;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** RenameRequest */
        RenameRequest: {
            /** Title */
            title: string;
        };
        /**
         * Role
         * @enum {string}
         */
        Role: "user" | "coach";
        /** SessionDetail */
        SessionDetail: {
            /** Ended At */
            ended_at?: string | null;
            /** Id */
            id: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Title */
            title?: string | null;
            /**
             * Turn Count
             * @default 0
             */
            turn_count: number;
            /** Turns */
            turns?: components["schemas"]["TurnOut"][];
        };
        /**
         * SessionMetrics
         * @description Aggregates behind the progress dashboard (A17).
         *
         *     Framed as practice trends, never as an assessment (docs/ETHICS.md).
         */
        SessionMetrics: {
            /** Event Counts */
            event_counts?: {
                [key: string]: number;
            };
            /**
             * Mean Fluency Load
             * @default 0
             */
            mean_fluency_load: number;
            /** Mean Speech Rate Wpm */
            mean_speech_rate_wpm?: number | null;
            /** Session Id */
            session_id: string;
            /**
             * Spoken Turns
             * @default 0
             */
            spoken_turns: number;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /**
             * Total Speech Ms
             * @default 0
             */
            total_speech_ms: number;
        };
        /** SessionOut */
        SessionOut: {
            /** Ended At */
            ended_at?: string | null;
            /** Id */
            id: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Title */
            title?: string | null;
            /**
             * Turn Count
             * @default 0
             */
            turn_count: number;
        };
        /**
         * StageTiming
         * @description Per-stage latency, collected for M10 and M12.
         *
         *     `stage` stays a plain string rather than the enum: a turn stored before a
         *     stage was named should still deserialise, and an unknown label is better
         *     rendered as "other" than raised as a validation error on someone's history.
         */
        StageTiming: {
            /** Ms */
            ms: number;
            /** Stage */
            stage: string;
        };
        /** TurnOut */
        TurnOut: {
            acoustic?: components["schemas"]["AcousticProfile"] | null;
            /** Citations */
            citations?: components["schemas"]["Citation"][];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: number;
            mode: components["schemas"]["Mode"];
            role: components["schemas"]["Role"];
            /** Text */
            text: string;
            /** Timings */
            timings?: components["schemas"]["StageTiming"][];
            /** Total Ms */
            total_ms?: number | null;
        };
        /** UpdateMeRequest */
        UpdateMeRequest: {
            /** Display Name */
            display_name?: string | null;
            /** Memory Enabled */
            memory_enabled?: boolean | null;
        };
        /** UserOut */
        UserOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Display Name */
            display_name: string | null;
            /** Email */
            email: string;
            /** Id */
            id: string;
            /** Memory Enabled */
            memory_enabled: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WsTicketOut */
        WsTicketOut: {
            /** Expires In */
            expires_in: number;
            /** Ticket */
            ticket: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    analyze_api_analyze_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_analyze_api_analyze_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    logout_all_api_auth_logout_all_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_api_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
        };
    };
    delete_me_api_auth_me_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeleteAccountRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_me_api_auth_me_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_me_api_auth_me_export_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    change_password_api_auth_me_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordChangeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_api_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
        };
    };
    register_api_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ws_ticket_api_auth_ws_ticket_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WsTicketOut"];
                };
            };
        };
    };
    chat_api_chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chat_audio_api_chat_audio_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_chat_audio_api_chat_audio_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    corpus_status_api_corpus_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    ingest_api_corpus_ingest_post: {
        parameters: {
            query?: {
                /** @description Drop the existing index first. Use after removing documents. */
                reset?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    manifest_api_corpus_manifest_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    search_api_corpus_search_get: {
        parameters: {
            query: {
                q: string;
                k?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Citation"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    acoustic_schema_api_schema_acoustic_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    list_sessions_api_sessions_get: {
        parameters: {
            query?: {
                limit?: number;
                q?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_session_api_sessions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionOut"];
                };
            };
        };
    };
    progress_api_sessions_progress_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProgressOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_session_api_sessions__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_session_api_sessions__session_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rename_session_api_sessions__session_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RenameRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    end_session_api_sessions__session_id__end_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    session_metrics_api_sessions__session_id__metrics_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionMetrics"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    status_api_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
